### ISSUE TITLE
 fs.readFileSync is not a function

### ISSUE THREAD

**Issue by dengzengjian** [najadojo/gltf-import-export#11]
when i used this tools in nodejs +vuejs ，it has accured a mistake ,it show  that  fs.readFileSync is not a function

when i find the problem  in the  code file exportProvider.js, the fs modules has not installed.
could u give me some sugestion

**Comment by najadojo** [comment]
I assume you are running the Vue application in the browser? the fs import is from Node.js and won't be available in that context. This package can run in your Node server if you upload the content process it and download the results the to browser. Additionally I'd happy take and changes so the package could execute in browser.

**Comment by dengzengjian** [comment]
> I assume you are running the Vue application in the browser? the fs import is from Node.js and won't be available in that context. This package can run in your Node server if you upload the content process it and download the results the to browser. Additionally I'd happy take and changes so the package could execute in browser.

Duplicate of #yes! I see，thank you!
