### ISSUE TITLE
No @types/gltf-import-export for Typescript

### ISSUE THREAD

**Issue by Sparcks** [najadojo/gltf-import-export#12]
Hi

I was trying this exporter out, but it seems that it doesn't have typings module for Typescript. When I did `npm install --save-dev @types/gltf-import-export` I got a 404 not found.

Are there any plans on making one available?
Thanks in advance.

Kind regards

**Comment by emackey** [comment]
@Sparcks This module is written in Typescript directly, it doesn't need a separate types import.

**Comment by Sparcks** [comment]
Hi @emackey he doesn't seem to find it: `Cannot find module 'gltf-import-export' or its corresponding type declarations.`

**Comment by najadojo** [comment]
Would please you explain in more detail how you are importing it?

**Comment by Sparcks** [comment]
@najadojo I'm sorry, I should've provided more detail indeed. But I have found the issue. My 'module' in my tsconfig wasn't set correctly. When I changed it to 'commonjs' it fixed the issue. I will close the ticket. Thanks for the help.
