### ISSUE TITLE
How to use command line tool?

### ISSUE THREAD

**Issue by ghost** [najadojo/gltf-import-export#16]
First off: Thanks for making this available!

I am able to clone the repo and build the project using "npm i" and then "npm run build", which produces a dist folder full of js and map files, but I don't see how to generate and/or run the command line tool. Do you have any hints on how to proceed?

**Comment by najadojo** [comment]
I use the npm published version:
```
$ npm install -g gltf-import-export
$ gltf-import-export
Usage: tool.js <file> [options]

Options:
      --version  Show version number                                   [boolean]
  -o, --output   Output filename                                        [string]
  -h, --help     Show help                                             [boolean]

Not enough non-option arguments: got 0, need at least 1
```
