### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by FUSLUTA** [najadojo/gltf-import-export#17]
I am a noob. Can someone help me with this?

First: the script is named ZZZZZZZZZZZZZ.js, so I can find it more easily.

When I do:
`node .\ZZZZZZZZZZZZZZZZ.js`

I get:

`SyntaxError: Cannot use import statement outside a module`

```
(node:13604) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
D:\HASHLIPS NFT NFT NFT NFT\Hbargutangs XXXXXXX - Beta prkt\gltf-import-export-master\ZZZZZZZZZZZZZZZZ.js:3
import { ConvertGLBtoGltf, ConvertGltfToGLB, ConvertToGLB} from 'gltf-import-export';
^^^^^^
```
using .mjs on `index.js` doesn't change anything. Doing "type":"module" in .json is not relevant. What to do?

**Comment by FUSLUTA** [comment]
Ok, so being a noob I found a package.json and added `"type":"module"` at the top, which made it work.
Now I get the error:
`SyntaxError: The requested module 'gltf-import-export' does not provide an export named 'ConvertToGLB'`

![image](https://user-images.githubusercontent.com/42798106/140618827-383fd697-887b-4ad0-b4c5-9cf9e70020ad.png)

But it does. If I take away that one from the import it doesn't find the other ones either.

**Comment by emackey** [comment]
Are you just trying to run this from the command line?  There are [command-line instructions](https://github.com/najadojo/gltf-import-export/blob/master/README.md#command-line-tool).

You can actually run this without installing it, via npx (that ships with NodeJS).  For example:

`npx gltf-import-export`

**Comment by FUSLUTA** [comment]
My friend solved the script not working with some `node -r esm` stuff.

I don't know really what esm is but if anyone else runs into the issue esm is a solution.
