### ISSUE TITLE
2c.glb in npm package

### ISSUE THREAD

**Issue by emackey** [najadojo/gltf-import-export#19]
Hi @najadojo, looks like the glTF 2-cylinder engine sample model got accidentally published with the last npm release.

The npm [1.0.18](https://www.npmjs.com/package/gltf-import-export/v/1.0.18) release was 52kb, and the npm [1.0.19](https://www.npmjs.com/package/gltf-import-export/v/1.0.19) release is 1.89 MB.  The size difference is a new file "2c.glb" that looks to be one of the sample models.

Not a big deal, but would be nice to recover the space in a future version.

**Comment by najadojo** [comment]
@emackey  Sorry about that I've added 1.0.20 which removes that file.
