### ISSUE TITLE
Materials not detected

### ISSUE THREAD

**Issue by fabiensabatie** [najadojo/gltf-import-export#21]
Whenever I use this model :  [tree.zip](https://github.com/najadojo/gltf-import-export/files/14521198/tree.zip)

The material on it isn't converted and does not show up in the gltf file. Using an online service to convert the glb to gltf, i noticed that the file uses two extensions : 
```
"extensionsUsed": [
        "KHR_materials_volume",
        "FB_ngon_encoding"
],
```

And the material shows up correctly 

```
"materials": [
        {
            "name": "material"
        }
    ],
```

Any idea why ? :D

**Comment by najadojo** [comment]
Unfortunately, I changed jobs a little while back and my new employer doesn't allow open-source contributions. I'd suggest forking this repo to fix this issue. 
cc @emackey

**Comment by fabiensabatie** [comment]
@najadojo leave your employer 😂

Alright I was just being lazy, I will need to make it work soon anyways, so i'll dive in the code and make a PR, probably next week.

Have a good one guys.
