### ISSUE TITLE
Support base64-encoded binary GLBs

### ISSUE THREAD

**Issue by emackey** [najadojo/gltf-import-export#7]
Issue https://github.com/KhronosGroup/glTF-Blender-IO/issues/61 talks about Blender exporting GLBs with base64-encoded data URIs in the JSON part.  This doesn't strike me as the ideal way to structure a GLB, but, it looks like the glTF ecosystem may have some number of these in the wild already.

It looks like the GLB importer here fails to load these, producing an empty `.bin` file and `"byteLength": 0` in the resulting glTF.

Sample model from that issue:  [glb_cubes.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2544536/glb_cubes.zip) (use `_io_2_79_cube.glb`)

**Comment by najadojo** [comment]
Resolved in in 1.0.14. Thanks for the report @emackey!
